### ISSUE TITLE
How to collection extracted file in manager or logger?

### ISSUE THREAD

**Issue by Center-Sun** [zeek/zeekctl#37]
Hi there, I'm try to enable extract-all-file.zeek on worker , and it's worked. 

when cluster start capture traffic , i can see the extracted file in /usr/local/zeek/spool/worker-1-1/extract_files on every worker.
but they are not  aggregated to manager node,and will be cleaned when stop .

How can i aggregated those file in manager or logger node?

**Comment by ckreibich** [comment]
Apologies for letting this issue linger this long. We don't use GitHub issues for support questions. Please post questions such as this one on Slack or our Discourse server. The Zeek developers and users will be happy to help. You can join here:

Slack: https://zeek.org/community/
Discourse: https://community.zeek.org/

Thanks!
