### ISSUE TITLE
Restarting all nodes upon crash of one

### ISSUE THREAD

**Issue by chazoz** [zeek/zeekctl#42]
Hello

I was wondering about the most suitable way to achieve the following :

1. Run zeekctl cron
2. If a zeek instance has crashed or stopped, run a custome script and restart the entire cluster.

Thank you

**Comment by ckreibich** [comment]
Hi there,

You'll need to script some form of change detection on the `zeekctl cron` (or `zeekctl status`) output and initiate a cluster restart when it triggers.

Please note: we don't use GitHub issues for support questions. Please post questions such as this one on Slack or our Discourse server. The Zeek developers and users will be happy to help. You can join here:

Slack: https://zeek.org/community/
Discourse: https://community.zeek.org/

Thanks!
