### ISSUE TITLE
[Error] module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'

### ISSUE THREAD

**Issue by mute019** [zeek/zeekctl#60]
I replaced the SafeConfigParser() with RawConfigParser() in the config.py and Zeekctl started working. Right now, I am wondering about the issues I might face for changing it in the future. I would love to see a feedback from your side about it. Thank You!

**Comment by mute019** [comment]
Okay, I will open a pull request tomorrow.

**Comment by ckreibich** [comment]
It's pretty funny — the deprecation warning comes from `warnings.warn(..., DeprecationWarning)`, which only shows when happening in `__main__` or when `PYTHONDEVMODE=1`:
```
$ zeekctl
Hint: Run the zeekctl "deploy" command to get started.

Welcome to ZeekControl 2.5.0-24

Type "help" for help.

[ZeekControl] >
```
```
$ PYTHONDEVMODE=1 zeekctl
/home/christian/inst/opt/zeek/lib64/zeek/python/zeekctl/ZeekControl/config.py:389: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in Python 3.12. Use ConfigParser directly instead.
  config = configparser.SafeConfigParser()
Hint: Run the zeekctl "deploy" command to get started.

Welcome to ZeekControl 2.5.0-24

Type "help" for help.

[ZeekControl] >
```
They didn't yell loud enough for us to notice...

**Comment by mute019** [comment]
Okay, another issue, I guess. In the documentation, it is not explicit mentioned in the documentation of the zeekctl whether we should run zeekctl using sudo command. 

Without sudo I am able to access the zeekctl but I am still facing an issue with permissions.

`zeekctl 
Error: failed to write file: [Errno 13] Permission denied: '/usr/local/zeek/spool/.zeekctl-config.sh.tmp'

Welcome to ZeekControl 2.5.0-39

Type "help" for help.

[ZeekControl] > deploy	
Error: failed to read lock file: [Errno 2] No such file or directory: '/usr/local/zeek/spool/lock'
Error: Unable to get lock
[ZeekControl] > exit
`

Hence, the conclusion:

With RawConfigParser only root can access zeekctl.
With ConfigParser both root and normal user are able access zeekctl but the normal user is facing issues with permissions.

**Comment by mute019** [comment]
> Okay, another issue, I guess. In the documentation, it is not explicit mentioned in the documentation of the zeekctl whether we should run zeekctl using sudo command.
> 
> Without sudo I am able to access the zeekctl but I am still facing an issue with permissions.
> 
> `zeekctl Error: failed to write file: [Errno 13] Permission denied: '/usr/local/zeek/spool/.zeekctl-config.sh.tmp'
> 
> Welcome to ZeekControl 2.5.0-39
> 
> Type "help" for help.
> 
> [ZeekControl] > deploy Error: failed to read lock file: [Errno 2] No such file or directory: '/usr/local/zeek/spool/lock' Error: Unable to get lock [ZeekControl] > exit `
> 
> Hence, the conclusion:
> 
> With RawConfigParser only root can access zeekctl. With ConfigParser both root and normal user are able access zeekctl but the normal user is facing issues with permissions.

Sorry, I overlooked the FAQ section in the documentation.
