### ISSUE TITLE
`post-terminate`'s processing of a node's `spool/zeek/` state discards extracted files

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeekctl#65]
When tucking file extraction onto the default `local.zeek`, for example by adding
```
@load frameworks/files/extract-all-files
```
the extracted files are lost when shutting down Zeek nodes. The default extraction destination is `spool/zeek/extracted_files/`, and `zeekctl`'s `post-terminate` processor for cleaning up the spool first moves the entirety of `spool/zeek` to a temp directory, then processes the logs in it (via `archive-log`), and then discards the temp directory and any extracted files with it.

An easy fix could be for `zeekctl` to adjust the `FileExtract::prefix` to something that separates that location from its log processing. A bigger change would be to build out proper post-processing for finished files.

**Comment by awelzel** [comment]
> An easy fix could be for zeekctl to adjust the FileExtract::prefix to something that separates that location from its log processing.

I'm swinging between moving `spool/extract_files` and `spool/extract_files/<node>/`, with slight preferences for the latter.

> A bigger change would be to build out proper post-processing for finished files.

Isn't logic often implemented via `file_state_remove()` in custom scripts? In a default setup it appears even difficult to determine (as an external consumer inspecting the filesystem) if a file has finished extraction or not.

**Comment by ckreibich** [comment]
> `spool/extract_files/<node>/`

Yeah I was thinking something similar — at least some separation so it doesn't all pile up in one place. This sounds good to me.

> Isn't logic often implemented via file_state_remove() in custom scripts?

Yeah.

> In a default setup it appears even difficult to determine (as an external consumer inspecting the filesystem) if a file has finished extraction or not.

Yeah exactly — I read over the extractor code and was a bit surprised by that. Seems we could fairly easily do better there.
